name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: vars
        shell: bash
        run: |
          VERSION="$(sed -n 's/FROM .*postgresql:\(16.3\)$/\1/p' Dockerfile)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          provenance: false
          cache-from: type=registry,ref=ghcr.io/dn0/cloudnative-pg-timescaledb:latest
          cache-to: type=inline
          tags: |
            ghcr.io/dn0/cloudnative-pg-timescaledb:${{ steps.vars.outputs.version }}
            ghcr.io/dn0/cloudnative-pg-timescaledb:latest

